version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.3
    steps:
      - checkout
      - run:
          name: Enable go1.12 modules
          command: |
            echo 'export GO111MODULE=on' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Test
          command: make test
      - run:
          name: Lint
          command: make lint
